spring.application.name=jfs
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/products}
spring.datasource.url=${SPRING_DATASOURCE_URL}

#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

cors.allowed.origins=*
cors.allowed.methods=*

server.max-http-request-header-size=65KB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB

# AWS S3 Configuration (MinIO for local development)
aws.region=us-east-1
aws.s3.bucket=product-images
aws.s3.endpoint-override=${AWS_S3_ENDPOINT_OVERRIDE:http://minio:9000}
aws.s3.path-style-enabled=true

inference.base-url=${INFERENCE_BASE_URL:http://inference:8000}
server.port=5050

#spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.startup-producer.enabled=false
app.kafka.enabled=${APP_KAFKA_ENABLED:false}



app.exit-after-send=${APP_EXIT_AFTER_SEND:false}

management.endpoints.web.exposure.include=mappings,health,info

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.ack-mode=manual
logging.level.org.springframework.kafka=INFO

# Show Spring Cache activity (hits, misses, puts, evictions)
logging.level.org.springframework.cache=TRACE

# Show your service logs (where we?ll print "DB HIT")
logging.level.com.thurman.product=INFO


